AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/ClassLength:
  Exclude:
    - spec/servirtium_servlet.rb

Style/GlobalVars:
  Exclude:
    - spec/spec_helper.rb